### ISSUE TITLE
Timeout for "Page numbers relative to the groups"

### ISSUE THREAD

**Issue by Prinzhorn** [jsreport/playground#21]
Keep getting an error when rendering the example https://playground.jsreport.net/w/admin/k1fGHFZp linked here https://jsreport.net/learn/pdf-utils?version=3.0.0

All I do is hit "Run"

```
Render Preview failed. Got not ok response, status: 504

Error: Got not ok response, status: 504
    at https://playground.jsreport.net/studio/assets/client.33aa66b0c01e4d50d061.js:352:65493
    at m (https://playground.jsreport.net/studio/assets/client.33aa66b0c01e4d50d061.js:315:103878)
    at Generator._invoke (https://playground.jsreport.net/studio/assets/client.33aa66b0c01e4d50d061.js:315:103631)
    at Generator.forEach.e.<computed> [as next] (https://playground.jsreport.net/studio/assets/client.33aa66b0c01e4d50d061.js:315:104058)
    at i (https://playground.jsreport.net/studio/assets/client.33aa66b0c01e4d50d061.js:3:388629)
    at https://playground.jsreport.net/studio/assets/client.33aa66b0c01e4d50d061.js:3:388726
```

**Comment by pofider** [comment]
Thank you.
We are working on some related regression issues in the v3 beta.
We will release a hotfix soon.

**Comment by pofider** [comment]
This was an old problem. I am closing it.
